name: Build and Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Build and Deploy to Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
<<<<<<< HEAD
        run: npm ci
=======
        run: npm install
>>>>>>> ab2c6215475665959808ffdd931999055db38c68

      - name: Build
        run: npm run build
        env:
          REACT_APP_ENV: production

      - name: Push build to production branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: production
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Production Build: ({sha}) {msg}"
