name: Pull Request Validation and Development Build
on:
  pull_request:
    branches:
      - main
jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Validate and Build for Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install HTML and CSS validators
        run: |
          pip install html5validator
          npm install -g stylelint stylelint-config-standard
        continue-on-error: false

      - name: Create Stylelint configuration
        run: |
          echo '{"extends": "stylelint-config-standard"}' > .stylelintrc.json
        continue-on-error: false

      - name: Validate HTML
        run: html5validator --root src
        continue-on-error: false

      - name: Validate and fix CSS
        run: stylelint "src/**/*.css" --fix
        if: always()

      - name: Copy static assets to dist
        run: |
          mkdir -p dist
          cp -r src/* dist/
        continue-on-error: false

      - name: Push build folder to development branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: development
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Development Build for PR #{pr_number}: ({sha}) {msg}"
        with:
          pr_number: ${{ github.event.pull_request.number }}
