name: Pull Request Validation and Development Build
on:
  pull_request:
    branches:
      - main
jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Validate and Build for Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_ENV: development

      - name: Push build to development branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: development
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Development Build for PR #{pr_number}: ({sha}) {msg}"
        with:
          pr_number: ${{ github.event.pull_request.number }}
